Repository ochoWhat2do/what2do, pull requests merged in 2023-08, with the labels that each got.

#4 [feature] 엔티티 초기 개발
  src/main/java/com/ocho/what2do/category/entity/Category.java
  src/main/java/com/ocho/what2do/comment/entity/Comment.java
  src/main/java/com/ocho/what2do/comment/entity/CommentLike.java
  src/main/java/com/ocho/what2do/review/entity/Review.java
  src/main/java/com/ocho/what2do/review/entity/ReviewLike.java
  src/main/java/com/ocho/what2do/store/dto/StoreApiDto.java
  src/main/java/com/ocho/what2do/store/entity/Store.java
  src/main/java/com/ocho/what2do/storecategory/entity/StoreCategory.java
  src/main/java/com/ocho/what2do/storeuser/entity/StoreUser.java
Labels: feature, initial

#13 [feature] 네이버 검색 api
  build.gradle
  src/main/java/com/ocho/what2do/common/config/WebSecurityConfig.java
  src/main/java/com/ocho/what2do/common/naver/controller/NaverApiController.java
  src/main/java/com/ocho/what2do/common/naver/dto/ItemDto.java
  src/main/java/com/ocho/what2do/common/naver/service/NaverApiService.java
Labels: feature

#16 [feature] 다음 검색 api
  src/main/java/com/ocho/what2do/common/config/RestTemplateConfig.java
  src/main/java/com/ocho/what2do/common/config/WebSecurityConfig.java
  src/main/java/com/ocho/what2do/common/daum/controller/DaumApiController.java
  src/main/java/com/ocho/what2do/common/daum/dto/DaumDto.java
  src/main/java/com/ocho/what2do/common/daum/service/DaumApiService.java
  src/main/java/com/ocho/what2do/common/daum/service/DaumApiServiceImpl.java
  src/main/java/com/ocho/what2do/common/naver/controller/NaverApiController.java
  src/main/java/com/ocho/what2do/common/naver/dto/NaverDto.java
  src/main/java/com/ocho/what2do/common/naver/service/NaverApiService.java
  src/main/java/com/ocho/what2do/common/naver/service/NaverApiServiceImpl.java
Labels: feature

#34 [feature] 관리자 기능 추가
  src/main/java/com/ocho/what2do/admin/controller/AdminStoreController.java
  src/main/java/com/ocho/what2do/admin/controller/AdminUserController.java
  src/main/java/com/ocho/what2do/admin/dto/AdminStoreListResponseDto.java
  src/main/java/com/ocho/what2do/admin/dto/AdminStoreRequestDto.java
  src/main/java/com/ocho/what2do/admin/dto/AdminStoreResponseDto.java
  src/main/java/com/ocho/what2do/admin/dto/AdminStoreViewResponseDto.java
  src/main/java/com/ocho/what2do/admin/dto/TokenRequestDto.java
  src/main/java/com/ocho/what2do/admin/dto/UserLockRequestDto.java
  src/main/java/com/ocho/what2do/admin/dto/UserRoleRequestDto.java
  src/main/java/com/ocho/what2do/admin/service/AdminStoreService.java
  src/main/java/com/ocho/what2do/admin/service/AdminStoreServiceImpl.java
  src/main/java/com/ocho/what2do/admin/service/AdminUserService.java
  src/main/java/com/ocho/what2do/admin/service/AdminUserServiceImpl.java
  src/main/java/com/ocho/what2do/common/config/WebSecurityConfig.java
  src/main/java/com/ocho/what2do/common/jwt/JwtAuthorizationFilter.java
  src/main/java/com/ocho/what2do/common/message/CustomErrorCode.java
  src/main/java/com/ocho/what2do/common/security/handler/LoginSuccessHandler.java
  src/main/java/com/ocho/what2do/store/controller/StoreController.java
  src/main/java/com/ocho/what2do/store/entity/Store.java
  src/main/java/com/ocho/what2do/user/entity/User.java
  src/test/java/com/ocho/what2do/admin/AdminStoreServiceImplTest.java
  src/test/java/com/ocho/what2do/store/service/StoreServiceImplTest.java
Labels: enhancement, feature

#36 [feature] 다음 api 성능 개선
  src/main/java/com/ocho/what2do/common/config/WebSecurityConfig.java
  src/main/java/com/ocho/what2do/common/daum/controller/DaumApiController.java
  src/main/java/com/ocho/what2do/common/daum/entity/ApiStore.java
  src/main/java/com/ocho/what2do/common/daum/repository/ApiStoreRepository.java
  src/main/java/com/ocho/what2do/common/daum/service/DaumApiService.java
  src/main/java/com/ocho/what2do/common/daum/service/DaumApiServiceImpl.java
  src/main/java/com/ocho/what2do/store/controller/StoreController.java
  src/main/java/com/ocho/what2do/store/dto/StoreApiDto.java
  src/main/java/com/ocho/what2do/store/dto/StoreRequestDto.java
  src/main/java/com/ocho/what2do/store/dto/StoreResponseDto.java
  src/main/java/com/ocho/what2do/store/entity/Store.java
  src/main/java/com/ocho/what2do/store/repository/StoreRepository.java
  src/main/java/com/ocho/what2do/store/service/StoreService.java
  src/main/java/com/ocho/what2do/store/service/StoreServiceImpl.java
Labels: feature
