Repository ochoWhat2do/what2do, pull requests merged in 2023-09, with the labels that each got.

#42 [feature] 검색 기능 업데이트
  src/main/java/com/ocho/what2do/common/config/WebSecurityConfig.java
  src/main/java/com/ocho/what2do/common/daum/repository/ApiStoreRepository.java
  src/main/java/com/ocho/what2do/store/controller/StoreController.java
  src/main/java/com/ocho/what2do/store/dto/StoreCategoryListResponseDto.java
  src/main/java/com/ocho/what2do/store/service/StoreService.java
  src/main/java/com/ocho/what2do/store/service/StoreServiceImpl.java
Labels: feature

#44 [update] 페이징 기능 추가
  src/main/java/com/ocho/what2do/common/config/PageConfig.java
  src/main/java/com/ocho/what2do/common/daum/repository/ApiStoreRepository.java
  src/main/java/com/ocho/what2do/store/controller/StoreController.java
  src/main/java/com/ocho/what2do/store/service/StoreService.java
  src/main/java/com/ocho/what2do/store/service/StoreServiceImpl.java
Labels: update

#51 [update] 다음 API 개선
  src/main/java/com/ocho/what2do/common/daum/controller/DaumApiController.java
  src/main/java/com/ocho/what2do/common/daum/repository/ApiStoreRepository.java
  src/main/java/com/ocho/what2do/common/daum/service/DaumApiService.java
  src/main/java/com/ocho/what2do/common/daum/service/DaumApiServiceImpl.java
  src/main/java/com/ocho/what2do/common/message/CustomErrorCode.java
  src/main/java/com/ocho/what2do/store/dto/StoreCategoryListResponseDto.java
  src/main/java/com/ocho/what2do/store/dto/StoreListResponseDto.java
  src/main/java/com/ocho/what2do/store/service/StoreServiceImpl.java
Labels: update

#72 [fix] 페이징 기능 수정
  build.gradle
  src/main/java/com/ocho/what2do/common/aop/TimeTrace.java
  src/main/java/com/ocho/what2do/common/aop/TimeTraceAspect.java
  src/main/java/com/ocho/what2do/common/config/CacheConfig.java
  src/main/java/com/ocho/what2do/common/daum/repository/ApiStoreRepository.java
  src/main/java/com/ocho/what2do/common/daum/service/DaumApiServiceImpl.java
  src/main/java/com/ocho/what2do/common/message/CustomErrorCode.java
  src/main/java/com/ocho/what2do/review/service/ReviewServiceImpl.java
  src/main/java/com/ocho/what2do/store/dto/StoreCategoryListResponseDto.java
  src/main/java/com/ocho/what2do/store/dto/StoreListResponseDto.java
  src/main/java/com/ocho/what2do/store/repository/StoreRepository.java
  src/main/java/com/ocho/what2do/store/service/StoreService.java
  src/main/java/com/ocho/what2do/store/service/StoreServiceImpl.java
  src/main/java/com/ocho/what2do/user/repository/UserRepository.java
  src/main/java/com/ocho/what2do/user/service/UserServiceImpl.java
Labels: bug, fix

#71 [fix] 캐시 메모리
  src/main/java/com/ocho/what2do/common/config/CacheConfig.java
Labels: bug, fix

#91 [fix] 가게 찜하기 기능 동작을 위한 수정
  src/main/java/com/ocho/what2do/store/controller/StoreController.java
  src/main/java/com/ocho/what2do/store/dto/StoreResponseDto.java
  src/main/java/com/ocho/what2do/store/service/StoreService.java
  src/main/java/com/ocho/what2do/store/service/StoreServiceImpl.java
  src/main/java/com/ocho/what2do/storefavorite/dto/StoreFavoriteResponseDto.java
Labels: fix

#101 [refactor] Kakao Api 리팩토링 및 책임분리
  src/main/java/com/ocho/what2do/store/controller/KakaoApiController.java
  src/main/java/com/ocho/what2do/store/dto/StoreResponseDto.java
  src/main/java/com/ocho/what2do/store/entity/ApiStore.java
  src/main/java/com/ocho/what2do/store/repository/ApiStoreRepository.java
  src/main/java/com/ocho/what2do/store/repository/StoreRepositoryImpl.java
  src/main/java/com/ocho/what2do/store/service/KakaoApiService.java
  src/main/java/com/ocho/what2do/store/service/KakaoApiServiceImpl.java
  src/main/java/com/ocho/what2do/store/service/StoreService.java
  src/main/java/com/ocho/what2do/store/service/StoreServiceImpl.java
  src/main/java/com/ocho/what2do/store/util/KakaoUtil.java
Labels: refactor

#114 [update] 캐시 기능 개선
  src/main/java/com/ocho/what2do/admin/controller/AdminStoreController.java
  src/main/java/com/ocho/what2do/admin/dto/AdminApiStoreListResponseDto.java
  src/main/java/com/ocho/what2do/admin/dto/AdminApiStoreRequestDto.java
  src/main/java/com/ocho/what2do/admin/dto/AdminApiStoreResponseDto.java
  src/main/java/com/ocho/what2do/admin/dto/AdminApiStoreViewResponseDto.java
  src/main/java/com/ocho/what2do/admin/service/AdminStoreService.java
  src/main/java/com/ocho/what2do/admin/service/AdminStoreServiceImpl.java
  src/main/java/com/ocho/what2do/comment/dto/CommentListResponseDto.java
  src/main/java/com/ocho/what2do/common/config/CacheConfig.java
  src/main/java/com/ocho/what2do/common/file/CustomMultipartFile.java
  src/main/java/com/ocho/what2do/common/file/FileUploader.java
  src/main/java/com/ocho/what2do/common/jwt/JwtAuthenticationFilter.java
  src/main/java/com/ocho/what2do/common/redis/RedisUtil.java
  src/main/java/com/ocho/what2do/common/sceduler/StoreImageScheduler.java
  src/main/java/com/ocho/what2do/common/security/UserDetailsImpl.java
  src/main/java/com/ocho/what2do/common/security/handler/LoginSuccessHandler.java
  src/main/java/com/ocho/what2do/review/dto/ReviewListResponseDto.java
  src/main/java/com/ocho/what2do/review/entity/Review.java
  src/main/java/com/ocho/what2do/review/entity/ReviewLike.java
  src/main/java/com/ocho/what2do/review/service/ReviewService.java
  src/main/java/com/ocho/what2do/review/service/ReviewServiceImpl.java
  src/main/java/com/ocho/what2do/store/controller/KakaoApiController.java
  src/main/java/com/ocho/what2do/store/dto/StoreResponseDto.java
  src/main/java/com/ocho/what2do/store/entity/ApiStore.java
  src/main/java/com/ocho/what2do/store/repository/ApiStoreRepository.java
  src/main/java/com/ocho/what2do/store/repository/StoreRepositoryImpl.java
  src/main/java/com/ocho/what2do/store/service/KakaoApiServiceImpl.java
  src/main/java/com/ocho/what2do/store/service/ScheduleApiStoreService.java
  src/main/java/com/ocho/what2do/store/service/ScheduleApiStoreServiceImpl.java
  src/main/java/com/ocho/what2do/store/service/StoreService.java
  src/main/java/com/ocho/what2do/store/service/StoreServiceImpl.java
  src/main/java/com/ocho/what2do/store/util/KakaoUtil.java
  src/main/java/com/ocho/what2do/storefavorite/entity/StoreFavorite.java
  src/main/java/com/ocho/what2do/user/dto/SignupResponseDto.java
  src/main/java/com/ocho/what2do/userpassword/entity/UserPassword.java
  src/main/java/com/ocho/what2do/userpassword/repository/UserPasswordRepository.java
Labels: refactor, update

#116 [update] Cache 기능 개선
  build.gradle
  src/main/java/com/ocho/what2do/What2doApplication.java
  src/main/java/com/ocho/what2do/common/cache/CacheConfig.java
  src/main/java/com/ocho/what2do/common/cache/CacheType.java
  src/main/java/com/ocho/what2do/common/config/CacheConfig.java
  src/main/java/com/ocho/what2do/store/repository/ApiStoreRepository.java
  src/main/java/com/ocho/what2do/store/service/KakaoApiServiceImpl.java
Labels: update
